### ISSUE TITLE
How can I make the code work when wearing glove?

### ISSUE THREAD

**Issue by DilaraAlbayrak** [sashagaz/Hand_Detection#4]

**Comment by sashagaz** [comment]
Hey @DilaraSina , with a glove it should work actually even better. If you read the description, the code is based on color filtering. You need to check which part of the code gets the contour based on color, and change the thresholds for your gloves colors. Hope it helps, Sasha

**Comment by DilaraAlbayrak** [comment]
Thanks. Actually, All i need is detecting and tracking hand, finger movement/gestures are not even necessary. I have checked the script, things related to color are below (line 55 in the script):

`     mask2 = cv2.inRange(hsv,np.array([2,50,50]),np.array([15,255,255]))`

How should I convert that for a gray or black glove? I am specifically asking because I am not clear about color space. As far as I see, it is HSV but aren't ranges of `s` and `v` values between [0 100], are they, here there is also 255 value?

Besides that probably this line is irrelevant but I could not find any line that deals with color.


Thanks in advance.

**Comment by DilaraAlbayrak** [comment]
I misunderstood the [0 100] range, I will try it, I hope I can make it work for gray or black glove.

**Comment by DilaraAlbayrak** [comment]
I have try with a range that contains black, I have got below error:

`   File "HandDetection.py", line 94, in <module>
    cnts = contours[ci]
    IndexError: list index out of range
`
